// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using proyef.Context;

#nullable disable

namespace proyef.Migrations
{
    [DbContext(typeof(TareaContext))]
    [Migration("20230324154718_Initialdata")]
    partial class Initialdata
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("proyef.Models.Categoria", b =>
                {
                    b.Property<Guid>("CategoriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("Peso")
                        .HasColumnType("int");

                    b.HasKey("CategoriaId");

                    b.ToTable("Categoria", (string)null);

                    b.HasData(
                        new
                        {
                            CategoriaId = new Guid("71c87875-4439-4d7c-ba96-f8ba9136dbaa"),
                            Nombre = "Pendientes",
                            Peso = 20
                        },
                        new
                        {
                            CategoriaId = new Guid("71c87875-4439-4d7c-ba96-f8ba9136db02"),
                            Nombre = "Personales",
                            Peso = 20
                        });
                });

            modelBuilder.Entity("proyef.Models.Tarea", b =>
                {
                    b.Property<Guid>("TareaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoriaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreado")
                        .HasColumnType("datetime2");

                    b.Property<int>("PrioridadTarea")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("TareaId");

                    b.HasIndex("CategoriaId");

                    b.ToTable("Tarea", (string)null);

                    b.HasData(
                        new
                        {
                            TareaId = new Guid("71c87875-4439-4d7c-ba96-f8ba9136db03"),
                            CategoriaId = new Guid("71c87875-4439-4d7c-ba96-f8ba9136db02"),
                            Desc = "tarea 1",
                            FechaCreado = new DateTime(2023, 3, 24, 10, 47, 18, 414, DateTimeKind.Local).AddTicks(2866),
                            PrioridadTarea = 1,
                            Titulo = "Ejercicio"
                        },
                        new
                        {
                            TareaId = new Guid("71c87875-4439-4d7c-ba96-f8ba9136db04"),
                            CategoriaId = new Guid("71c87875-4439-4d7c-ba96-f8ba9136dbaa"),
                            Desc = "tarea 2",
                            FechaCreado = new DateTime(2023, 3, 24, 10, 47, 18, 414, DateTimeKind.Local).AddTicks(2881),
                            PrioridadTarea = 0,
                            Titulo = "Supermercado"
                        });
                });

            modelBuilder.Entity("proyef.Models.Tarea", b =>
                {
                    b.HasOne("proyef.Models.Categoria", "Categoria")
                        .WithMany("Tareas")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("proyef.Models.Categoria", b =>
                {
                    b.Navigation("Tareas");
                });
#pragma warning restore 612, 618
        }
    }
}
